import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeDollarSign, FileText, Plus, ReceiptText, RefreshCw, Send, WalletCards } from "lucide-react";
import { DashboardShell } from "../components/dashboard/DashboardShell";
import { DatabasePageSkeleton } from "../components/ui/DatabasePageSkeleton";
import { useToast } from "../components/ui/ToastProvider";
import { listDealsFromDatabase } from "../features/deals/deal-api";
import type { Deal } from "../features/deals/deal-data";
import { createWorkflowContract, createWorkflowOffer, listWorkflowCommissions, listWorkflowContracts, listWorkflowOffers, listWorkflowPayments, recordWorkflowPayment, saveWorkflowCommission, setWorkflowContractStatus, updateWorkflowOffer, type WorkflowCommission, type WorkflowContract, type WorkflowOffer, type WorkflowPayment, createWorkflowPaymentSchedule } from "../features/workflow/workflow-api";

const money = (value: string | number, currency: "USD" | "IQD") => `${Number(value).toLocaleString("en-US", { maximumFractionDigits: 2 })}${currency === "USD" ? "$" : " IQD"}`;
const tabs = ["Offers", "Contracts", "Commissions", "Payments"] as const;
type Tab = typeof tabs[number];
const input = "mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-amber-500 focus:ring-4 focus:ring-amber-100";

export function TransactionWorkflowPage() {
  const toast = useToast();
  const [tab, setTab] = useState<Tab>("Offers");
  const [deals, setDeals] = useState<Deal[]>([]);
  const [offers, setOffers] = useState<WorkflowOffer[]>([]);
  const [contracts, setContracts] = useState<WorkflowContract[]>([]);
  const [commissions, setCommissions] = useState<WorkflowCommission[]>([]);
  const [payments, setPayments] = useState<WorkflowPayment[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [selectedDeal, setSelectedDeal] = useState("");
  const [amount, setAmount] = useState("");
  const [currency, setCurrency] = useState<"USD" | "IQD">("USD");
  const [offerConditions, setOfferConditions] = useState("");
  const [contractNumber, setContractNumber] = useState("");
  const [contractStart, setContractStart] = useState("");
  const [contractTerms, setContractTerms] = useState("");
  const [commissionMode, setCommissionMode] = useState<"PERCENTAGE" | "FIXED">("PERCENTAGE");
  const [commissionRate, setCommissionRate] = useState("2");
  const [paymentLabel, setPaymentLabel] = useState("Deposit");
  const [paymentDue, setPaymentDue] = useState("");
  const [recording, setRecording] = useState<WorkflowPayment | null>(null);

  async function load() {
    setLoading(true); setError("");
    try {
      const [dealRows, offerRows, contractRows, commissionRows, paymentRows] = await Promise.all([
        listDealsFromDatabase({ pageSize: 100 }), listWorkflowOffers(), listWorkflowContracts(), listWorkflowCommissions(), listWorkflowPayments(),
      ]);
      setDeals(dealRows); setOffers(offerRows); setContracts(contractRows); setCommissions(commissionRows); setPayments(paymentRows);
      if (!selectedDeal && dealRows[0]) setSelectedDeal(dealRows[0].id);
    } catch (caught) { const message = caught instanceof Error ? caught.message : "Could not load transaction workflow."; setError(message); toast.error(message); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);

  const selected = deals.find((deal) => deal.id === selectedDeal);
  const acceptedOffer = offers.find((offer) => offer.dealId === selectedDeal && offer.status === "ACCEPTED");
  const selectedCommission = commissions.find((item) => item.dealId === selectedDeal);
  const selectedContract = contracts.find((item) => item.dealId === selectedDeal);
  const selectedPayments = useMemo(() => payments.filter((item) => item.dealId === selectedDeal), [payments, selectedDeal]);

  async function createOffer() {
    if (!selectedDeal || !amount) return toast.error("Select a deal and enter an offer amount.");
    setSaving(true); try { const row = await createWorkflowOffer({ dealId: selectedDeal, amount: Number(amount), currency, conditions: offerConditions }); setOffers((current) => [row, ...current]); setAmount(""); setOfferConditions(""); toast.success("Offer saved to the database."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not create offer."); } finally { setSaving(false); }
  }
  async function changeOffer(offer: WorkflowOffer, status: string) {
    setSaving(true); try { const row = await updateWorkflowOffer(offer.id, { status }); setOffers((current) => current.map((item) => item.id === row.id ? row : item)); toast.success(`Offer marked ${status.toLowerCase()}.`); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not update offer."); } finally { setSaving(false); }
  }
  async function createContract() {
    if (!selected || !acceptedOffer || !contractNumber || !contractStart) return toast.error("Select a deal with an accepted offer, then enter contract number and start date.");
    setSaving(true); try { const row = await createWorkflowContract({ dealId: selected.id, offerId: acceptedOffer.id, clientId: selected.clientId, propertyId: selected.propertyId, contractNumber, contractType: selected.type === "Rental" ? "RENTAL" : "SALE", currency: acceptedOffer.currency, startDate: contractStart, terms: contractTerms, responsibleAgentId: selected.assignedAgent }); setContracts((current) => [row, ...current]); toast.success("Contract created as a database record."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not create contract."); } finally { setSaving(false); }
  }
  async function saveCommission() {
    if (!selected) return toast.error("Select a deal first.");
    setSaving(true); try { const row = await saveWorkflowCommission(selected.id, { mode: commissionMode, rate: commissionMode === "PERCENTAGE" ? Number(commissionRate) : 0, fixedAmount: commissionMode === "FIXED" ? Number(amount) : 0 }); setCommissions((current) => [row, ...current.filter((item) => item.dealId !== row.dealId)]); toast.success("Commission saved."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not save commission."); } finally { setSaving(false); }
  }
  async function createSchedule() {
    if (!selected || !amount || !paymentDue) return toast.error("Select a deal, amount and due date.");
    setSaving(true); try { const row = await createWorkflowPaymentSchedule({ dealId: selected.id, contractId: selectedContract?.id, label: paymentLabel, amount: Number(amount), currency, dueDate: paymentDue }); setPayments((current) => [row, ...current]); setAmount(""); toast.success("Payment schedule created."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not create payment schedule."); } finally { setSaving(false); }
  }
  async function recordPayment() {
    if (!recording || !amount) return;
    setSaving(true); try { await recordWorkflowPayment(recording.id, { amount: Number(amount), method: "BANK_TRANSFER" }); toast.success("Payment recorded."); setRecording(null); setAmount(""); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not record payment."); } finally { setSaving(false); }
  }
  if (loading) return <DashboardShell><DatabasePageSkeleton cards={4} /></DashboardShell>;

  return <DashboardShell><section className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold tracking-wide text-amber-700">TRANSACTION WORKFLOW · LIVE DATABASE</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Offers, Contracts & Finance</h1><p className="mt-2 max-w-3xl text-slate-600">A single workspace for the transaction lifecycle. Every offer, contract, commission and payment is persisted in PostgreSQL.</p></div><button onClick={() => void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 font-bold text-slate-700 hover:bg-slate-50"><RefreshCw size={17}/> Refresh</button></section>
  {error && <div role="alert" className="mt-5 flex items-center justify-between rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700"><span>{error}</span><button onClick={() => void load()} className="rounded-lg px-3 py-2 hover:bg-rose-100">Retry</button></div>}
  <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block max-w-2xl text-sm font-bold text-slate-700">Working deal<select className={input} value={selectedDeal} onChange={(e) => setSelectedDeal(e.target.value)}><option value="">Select a deal</option>{deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.title} · {deal.stage}</option>)}</select></label>{selected && <div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Deal value</p><p className="mt-1 font-bold">{money(selected.expectedValueMinor / 100, selected.currency)}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Offers</p><p className="mt-1 font-bold">{offers.filter((item) => item.dealId === selected.id).length}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Contract</p><p className="mt-1 font-bold">{selectedContract?.status ?? "Not created"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Commission</p><p className="mt-1 font-bold">{selectedCommission ? money(selectedCommission.calculatedAmount, selected.currency) : "Not set"}</p></div></div>}</section>
  <nav className="mt-6 grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2 md:grid-cols-4">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`min-h-11 rounded-xl px-4 text-sm font-bold ${tab === item ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-900"}`}>{item}</button>)}</nav>
  {tab === "Offers" && <section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Send size={18} className="text-amber-600"/><h2 className="font-bold">New offer</h2></div><label className="mt-5 block text-sm font-semibold">Amount<input className={input} type="number" min="0" value={amount} onChange={(e) => setAmount(e.target.value)}/></label><label className="mt-4 block text-sm font-semibold">Currency<select className={input} value={currency} onChange={(e) => setCurrency(e.target.value as "USD" | "IQD")}><option>USD</option><option>IQD</option></select></label><label className="mt-4 block text-sm font-semibold">Conditions<textarea className={`${input} min-h-24 py-3`} value={offerConditions} onChange={(e) => setOfferConditions(e.target.value)}/></label><button disabled={saving} onClick={() => void createOffer()} className="mt-5 min-h-11 w-full rounded-xl bg-amber-500 px-4 font-bold disabled:opacity-50"><Plus size={17} className="mr-2 inline"/>Create offer</button></div><div className="space-y-3">{offers.filter((item) => !selectedDeal || item.dealId === selectedDeal).map((offer) => <article key={offer.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-400">OFFER</p><p className="mt-1 text-xl font-bold">{money(offer.amount, offer.currency)}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{offer.status}</span></div>{offer.conditions && <p className="mt-3 text-sm text-slate-600">{offer.conditions}</p>}<div className="mt-4 flex flex-wrap gap-2">{offer.status !== "ACCEPTED" && <button disabled={saving} onClick={() => void changeOffer(offer, "ACCEPTED")} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Accept</button>}{offer.status === "DRAFT" && <button disabled={saving} onClick={() => void changeOffer(offer, "SENT")} className="rounded-lg bg-sky-50 px-3 py-2 text-xs font-bold text-sky-700">Mark sent</button>}</div></article>)}{offers.filter((item) => !selectedDeal || item.dealId === selectedDeal).length === 0 && <Empty icon={<Send size={30}/>} title="No offers yet" text="Create an offer for the selected deal."/>}</div></section>}
  {tab === "Contracts" && <section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><FileText size={18} className="text-amber-600"/><h2 className="font-bold">Create contract</h2></div><p className="mt-2 text-xs text-slate-500">Requires an accepted offer. Contract fields are saved to PostgreSQL.</p><input className={input} placeholder="Contract number" value={contractNumber} onChange={(e) => setContractNumber(e.target.value)}/><input className={input} type="date" value={contractStart} onChange={(e) => setContractStart(e.target.value)}/><textarea className={`${input} min-h-28 py-3`} placeholder="Terms" value={contractTerms} onChange={(e) => setContractTerms(e.target.value)}/><button disabled={saving || !acceptedOffer} onClick={() => void createContract()} className="mt-4 min-h-11 w-full rounded-xl bg-slate-950 px-4 font-bold text-white disabled:opacity-40">Create contract</button></div><div className="space-y-3">{contracts.filter((item) => !selectedDeal || item.dealId === selectedDeal).map((contract) => <article key={contract.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">{contract.contractNumber}</p><h2 className="mt-1 font-bold">{money(contract.agreedAmount, contract.currency)} · {contract.contractType}</h2></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold">{contract.status}</span></div><div className="mt-4 flex flex-wrap gap-2">{contract.status === "DRAFT" && <button disabled={saving} onClick={() => void setWorkflowContractStatus(contract.id, "UNDER_REVIEW").then((row) => { setContracts((current) => current.map((item) => item.id === row.id ? row : item)); toast.success("Contract moved to review."); })} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold">Send for review</button>}{contract.status === "UNDER_REVIEW" && <button disabled={saving} onClick={() => void setWorkflowContractStatus(contract.id, "READY_TO_SIGN").then((row) => { setContracts((current) => current.map((item) => item.id === row.id ? row : item)); toast.success("Contract ready to sign."); })} className="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Ready to sign</button>}{contract.status === "READY_TO_SIGN" && <button disabled={saving} onClick={() => void setWorkflowContractStatus(contract.id, "SIGNED").then((row) => { setContracts((current) => current.map((item) => item.id === row.id ? row : item)); toast.success("Contract marked signed."); })} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Mark signed</button>}</div></article>)}{contracts.filter((item) => !selectedDeal || item.dealId === selectedDeal).length === 0 && <Empty icon={<FileText size={30}/>} title="No contracts yet" text="Accept an offer, then create the contract."/>}</div></section>}
  {tab === "Commissions" && <section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BadgeDollarSign size={18} className="text-amber-600"/><h2 className="font-bold">Commission setup</h2></div><select className={input} value={commissionMode} onChange={(e) => setCommissionMode(e.target.value as "PERCENTAGE" | "FIXED")}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select>{commissionMode === "PERCENTAGE" ? <input className={input} type="number" min="0" step="0.01" value={commissionRate} onChange={(e) => setCommissionRate(e.target.value)} placeholder="Rate %"/> : <input className={input} type="number" min="0" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Fixed amount"/>}<button disabled={saving || !selected} onClick={() => void saveCommission()} className="mt-4 min-h-11 w-full rounded-xl bg-amber-500 font-bold">Save commission</button></div><div className="space-y-3">{commissions.filter((item) => !selectedDeal || item.dealId === selectedDeal).map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">{item.mode}</p><p className="mt-1 text-xl font-bold">{item.mode === "PERCENTAGE" ? `${item.rate}%` : money(item.fixedAmount, selected?.currency ?? "USD")}</p></div><span className="font-bold text-emerald-600">{money(item.calculatedAmount, selected?.currency ?? "USD")}</span></div></article>)}{commissions.filter((item) => !selectedDeal || item.dealId === selectedDeal).length === 0 && <Empty icon={<BadgeDollarSign size={30}/>} title="No commission configured" text="Set the agency commission for this deal."/>}</div></section>}
  {tab === "Payments" && <section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><WalletCards size={18} className="text-amber-600"/><h2 className="font-bold">Payment schedule</h2></div><input className={input} value={paymentLabel} onChange={(e) => setPaymentLabel(e.target.value)} placeholder="Label"/><input className={input} type="number" min="0" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount"/><select className={input} value={currency} onChange={(e) => setCurrency(e.target.value as "USD" | "IQD")}><option>USD</option><option>IQD</option></select><input className={input} type="date" value={paymentDue} onChange={(e) => setPaymentDue(e.target.value)}/><button disabled={saving || !selected} onClick={() => void createSchedule()} className="mt-4 min-h-11 w-full rounded-xl bg-amber-500 font-bold">Create schedule</button></div><div className="space-y-3">{selectedPayments.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">{item.label}</p><p className="mt-1 text-xl font-bold">{money(item.amount, item.currency)}</p><p className="mt-1 text-sm text-slate-500">Due {item.dueDate}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{item.status}</span></div><button disabled={saving || item.status === "PAID"} onClick={() => { setRecording(item); setAmount(""); }} className="mt-4 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 disabled:opacity-40">Record payment</button>{item.payments.length > 0 && <p className="mt-3 text-xs font-semibold text-slate-500">{item.payments.length} payment record(s)</p>}</article>)}{selectedPayments.length === 0 && <Empty icon={<ReceiptText size={30}/>} title="No payment schedules" text="Create a schedule after selecting a deal."/>}</div></section>}
  {recording && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Record payment</h2><p className="mt-2 text-sm text-slate-500">{recording.label} · scheduled {money(recording.amount, recording.currency)}</p><input className={input} type="number" min="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Paid amount"/><div className="mt-5 flex gap-3"><button onClick={() => setRecording(null)} className="min-h-11 flex-1 rounded-xl border border-slate-200 font-bold">Cancel</button><button disabled={saving} onClick={() => void recordPayment()} className="min-h-11 flex-1 rounded-xl bg-amber-500 font-bold">Save payment</button></div></div></div>}
  </DashboardShell>;
}
function Empty({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="mx-auto w-fit text-slate-400">{icon}</div><h2 className="mt-4 font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p></section>; }
